
-------------------------------------------
--- SALES ORDER HEADER --------------------
-------------------------------------------
MERGE INTO bo.sales_order_header as soh USING (
SELECT DISTINCT 
    $source_system_id AS source_system_id, 
    0 AS brand_party_id, 
    p.party_id AS customer_party_id,
    lp.party_id AS store_party_id, ---LOCATION party_id
    p.party_id AS bill_to_party_id,
    0 AS ship_to_party_id,
    0 AS order_dealer_party_id,
    '0' as brand_no,
    '0' as brand_no_type,
    t.TRANID as sales_order_no,
    'netsuite_tranid' as sales_order_no_type,
    NULL as sales_order_reference_no,
    NULL as sfdc_order_no,
    NULL as sfdc_order_no_type,
    NULL as upstream_sales_order_no,
    NULL as upstream_sales_order_no_type,
    NULL as sfdc_table_no,
    NULL as sfcc_order_no,
    NULL as salesforce_order_no,
    NULL as purchase_order_no,
    TO_VARCHAR(t.TRANSACTION_ID) as netsuite_order_no,
    t.IMARC_ORDER_CODE as imarc_order_no,
    t.TRANID as netsuite_salesorder_no,
    TO_VARCHAR(t.ENTITY_ID) as customer_no,
    'netsuite_entity_id' as customer_no_type,
    NULL as erp_customer_no,
    NULL as erp_customer_no_type,
    NULL as bill_to_customer_no,
    NULL as bill_to_customer_no_type,
    NULL as ship_to_customer_no,
    NULL as ship_to_customer_no_type,
    TO_VARCHAR(t.ENTITY_ID) as netsuite_customer_no,
    NULL as order_dealer_account_no,
    TO_VARCHAR(t.SALES_REP_ID) as sales_rep_no,
    'netsuite_sales_rep_id' as sales_rep_no_type,
    NULL as store_location_no,
    NULL as store_location_no_type,
    TO_VARCHAR(t.LOCATION_ID) as netsuite_sales_location_no,
    NULL as order_dealer_no,
    NULL as quote_no,
    NULL as quote_no_type,
    NULL as quote_transaction_no,
    NULL as quote_expiration,
    NULL as payment_terms_no,
    NULL as payment_terms_no_type,
    totals.total_line_item_count as order_line_count,
    totals.total_item_count as item_count,
    NULL as sale_status,
    NULL as sales_order_status,
    NULL as sfdc_status_code,
    t.STATUS as netsuite_sales_order_status,
    NULL as netsuite_status,
    NULL as email_transaction_no,
    NULL as shipping_method_no,
    NULL as shipping_method_no_type,
    NULL as parcel_shipping_method_no,
    NULL as parcel_shipping_method_no_type,
    TO_VARCHAR(t.SHIP_METHOD_ID) as netsuite_shipping_method_no,
    NULL as shipping_zone_code,
    lp.party_channel_name as sales_channel,
    NULL as customer_source,
    NULL as applied_promotion_no,
    NULL as promotion_no,
    NULL as promotion_no_type,
    NULL as discount_percent,
    NULL as opportunity_project_name,
    NULL as netsuite_account_source_no,
    c.SYMBOL as order_currency_code,
    NULL as after_discount_amount,
    NULL as custom_amount,
    NULL as custom_amount_name,
    NULL as discount_amount,
    NULL as IMARC_discount_amount,
    NULL as margin_amount,
    NULL as merchandise_amount,
    NULL as net_retail_amount,
    NULL as outstanding_payment_amount,
    NULL as payment_amount,
    NULL as retail_amount,
    totals.income_amount as sales_order_amount,
    totals.tax_amount as tax_total_amount,
    NULL as valid_order_payment_amount,
    totals.freight_amount as shipping_amount,
    NULL as tax_amount,
    NULL as bundled_est_ship_timestamp,
    NULL as est_delivery_max_timestamp,
    NULL as est_delivery_min_timestamp,
    TO_TIMESTAMP_NTZ(ESTIMATED_SHIP_DATE) as est_ship_timestamp,
    NULL as payment_request_timestamp,
    NULL as sfdc_effective_timestamp,
    NULL as sfdc_activated_timestamp,
    NULL as sfdc_created_timestamp,
    NULL as sfdc_last_modified_timestamp,
    NULL as est_delivery_timestamp,
    NULL as salesorder_placed_timestamp,
    NULL as quote_expiration_timestamp,
    NULL as netsuite_error_code,
    NULL as resale_template_no,
    NULL as sales_order_blob1,
    NULL as sales_order_blob1_name,
    NULL as sales_order_blob2,
    NULL as sales_order_blob2_name,
    TO_TIMESTAMP_NTZ(convert_timezone('America/Los_Angeles', current_timestamp)) as created_timestamp,
    TO_TIMESTAMP_NTZ(convert_timezone('America/Los_Angeles', current_timestamp)) as updated_timestamp,
    'sales_order_header_load' as created_process,
    'sales_order_header_update' as updated_process,
    TO_TIMESTAMP_NTZ(t.TRANDATE) as order_date,
    'netsuite_trandate' as order_date_type,
    TO_TIMESTAMP_NTZ(t.CREATE_DATE) as netsuite_created_timestamp,
    TO_TIMESTAMP_NTZ(t.LAST_MODIFIED_DATE) as netsuite_last_modified_timestamp,
    totals.income_amount_usd as sales_order_amount_usd,
    totals.tax_amount_usd as tax_total_amount_usd,
    totals.freight_amount_usd as shipping_amount_usd,
    t.ESD_DELTA as netsuite_esd_delta,
    TO_TIMESTAMP_NTZ(t.APPROVED_DATE) as netsuite_approved_date,
    TO_TIMESTAMP_NTZ(t.CLOSED) as netsuite_closed,
    t.CREATED_BY_ID as netsuite_created_by_no,
    t.CREATED_FROM_ID as netsuite_created_from_no,
    t.CURRENCY_ID as netsuite_currency_no,
    t.EMAIL as netsuite_email,
    t.EXCHANGE_RATE as netsuite_exchange_rate,
    t.FLOOR_SALE as netsuite_floor_sale,
    t.GLOBAL_ACCOUNT as netsuite_global_account,
    t.IS_EXCHANGE_ORDER as netsuite_is_exchange_order,
    t.IS_NON_POSTING as netsuite_is_non_posting,
    t.MEMO as netsuite_memo,
    t.ORDER_LOCATION_TEXT as netsuite_order_location_text,
    TO_TIMESTAMP_NTZ(t.ORIGINAL_ESTIMATED_SHIP_DATE) as netsuite_original_estimated_ship_date,
    t.ORIGINAL_SALES_ORDER_ID as netsuite_original_sales_order_no,
    t.PAYMENT_TERMS_ID as netsuite_payment_terms_no,
    t.PICK_UP as netsuite_pick_up,
    t.POS_STATUS_ID as netsuite_pos_status_no,
    t.PROMOTION_CODE as netsuite_promotion_code,
    t.PURCHASE_ORDER_TYPE_ID as netsuite_purchase_order_type_no,
    TO_TIMESTAMP_NTZ(t.QUOTE_DATE) as netsuite_quote_date,
    t.RELATED_TRANID as netsuite_related_tranid,
    TO_TIMESTAMP_NTZ(t.SALES_EFFECTIVE_DATE) as netsuite_sales_effective_date,
    t.SHIPADDRESS as netsuite_shipaddress,
    TO_TIMESTAMP_NTZ(t.SHIPMENT_RECEIVED) as netsuite_shipment_received,
    t.SHIPPING_ITEM_ID as netsuite_shipping_item_no,
    t.SOURCE_0 as netsuite_source_0,
    t.SPLIT_COMMISSION_PERCENT as netsuite_split_commission_percent,
    t.SPLIT_COMMISSION_REP_ID as netsuite_split_commission_rep_no,
    t.TRANSACTION_EXTID as netsuite_transaction_extid,
    t.TRANSACTION_TYPE as netsuite_transaction_type,
    t.VIP_ORDER as netsuite_vip_order,

    -- Eastern(ET) timezone version of timestamp fields
    NULL as quote_expiration_et,
    NULL as bundled_est_ship_timestamp_et,
    NULL as est_delivery_max_timestamp_et,
    NULL as est_delivery_min_timestamp_et,
    convert_timezone('America/Detroit', ESTIMATED_SHIP_DATE) as est_ship_timestamp_et,
    NULL as payment_request_timestamp_et,
    NULL as sfdc_effective_timestamp_et,
    NULL as sfdc_activated_timestamp_et,
    NULL as sfdc_created_timestamp_et,
    NULL as sfdc_last_modified_timestamp_et,
    NULL as est_delivery_timestamp_et,
    NULL as salesorder_placed_timestamp_et,
    NULL as quote_expiration_timestamp_et,
    convert_timezone('America/Detroit', current_timestamp) as created_timestamp_et,
    convert_timezone('America/Detroit', current_timestamp) as updated_timestamp_et,
    convert_timezone('America/Detroit', t.TRANDATE) as order_date_et,
    convert_timezone('America/Detroit', t.CREATE_DATE) as netsuite_created_timestamp_et,
    convert_timezone('America/Detroit', t.LAST_MODIFIED_DATE) as netsuite_last_modified_timestamp_et,
    convert_timezone('America/Detroit', t.APPROVED_DATE) as netsuite_approved_date_et,
    convert_timezone('America/Detroit', t.CLOSED) as netsuite_closed_et,
    convert_timezone('America/Detroit', t.ORIGINAL_ESTIMATED_SHIP_DATE) as netsuite_original_estimated_ship_date_et,
    convert_timezone('America/Detroit', t.QUOTE_DATE) as netsuite_quote_date_et,
    convert_timezone('America/Detroit', t.SALES_EFFECTIVE_DATE) as netsuite_sales_effective_date_et,
    convert_timezone('America/Detroit', t.SHIPMENT_RECEIVED) as netsuite_shipment_received_et,

    -- UTC timezone version of timestamp fields
    NULL as quote_expiration_utc,
    NULL as bundled_est_ship_timestamp_utc,
    NULL as est_delivery_max_timestamp_utc,
    NULL as est_delivery_min_timestamp_utc,
    convert_timezone('UTC', ESTIMATED_SHIP_DATE) as est_ship_timestamp_utc,
    NULL as payment_request_timestamp_utc,
    NULL as sfdc_effective_timestamp_utc,
    NULL as sfdc_activated_timestamp_utc,
    NULL as sfdc_created_timestamp_utc,
    NULL as sfdc_last_modified_timestamp_utc,
    NULL as est_delivery_timestamp_utc,
    NULL as salesorder_placed_timestamp_utc,
    NULL as quote_expiration_timestamp_utc,
    convert_timezone('UTC', current_timestamp) as created_timestamp_utc,
    convert_timezone('UTC', current_timestamp) as updated_timestamp_utc,
    convert_timezone('UTC', t.TRANDATE) as order_date_utc,
    convert_timezone('UTC', t.CREATE_DATE) as netsuite_created_timestamp_utc,
    convert_timezone('UTC', t.LAST_MODIFIED_DATE) as netsuite_last_modified_timestamp_utc,
    convert_timezone('UTC', t.APPROVED_DATE) as netsuite_approved_date_utc,
    convert_timezone('UTC', t.CLOSED) as netsuite_closed_utc,
    convert_timezone('UTC', t.ORIGINAL_ESTIMATED_SHIP_DATE) as netsuite_original_estimated_ship_date_utc,
    convert_timezone('UTC', t.QUOTE_DATE) as netsuite_quote_date_utc,
    convert_timezone('UTC', t.SALES_EFFECTIVE_DATE) as netsuite_sales_effective_date_utc,
    convert_timezone('UTC', t.SHIPMENT_RECEIVED) as netsuite_shipment_received_utc,

    'America/Los_Angeles' as org_data_source_timezone,
    'NETSUITE_LOCATION_CHANNEL_ID' as sales_channel_type
FROM RAW.NETSUITE_5TRAN_TRANSACTIONS t 
INNER JOIN RAW.NETSUITE_5TRAN_CURRENCIES c ON t.currency_id = c.currency_id
--Transaction Totals
LEFT JOIN 
    (select t.TRANSACTION_ID , t.TRANID , t.TRANDATE , sum(tl.amount * -1) as total_amount, 
    sum(case when collate(gl.ACCOUNTTYPE, 'en-ci') = 'Income' then tl.AMOUNT * -1 else 0 end) as income_amount,
    sum(case when collate(gl.ACCOUNTTYPE, 'en-ci') = 'Tax' then tl.AMOUNT * -1 else 0 end) as tax_amount,
    sum(case when collate(gl.ACCOUNTTYPE, 'en-ci') = 'Freight' then tl.AMOUNT * -1 else 0 end) as freight_amount,
    sum(case when collate(gl.ACCOUNTTYPE, 'en-ci') = 'Income' then tl.AMOUNT * -1  * t.EXCHANGE_RATE else 0 end) as income_amount_usd,
    sum(case when collate(gl.ACCOUNTTYPE, 'en-ci') = 'Tax' then tl.AMOUNT * -1  * t.EXCHANGE_RATE else 0 end) as tax_amount_usd,
    sum(case when collate(gl.ACCOUNTTYPE, 'en-ci') = 'Freight' then tl.AMOUNT * -1 * t.EXCHANGE_RATE else 0 end) as freight_amount_usd,
    SUM(case when collate(gl.ACCOUNTTYPE, 'en-ci')= 'Income' then tl.ITEM_COUNT * -1 else 0 end) as total_item_count,
    count(case when collate(gl.ACCOUNTTYPE, 'en-ci')= 'Income' then tl.ITEM_COUNT * -1 else NULL end) as total_line_item_count
    FROM 
    RAW.NETSUITE_5TRAN_TRANSACTIONS t
    JOIN RAW.NETSUITE_5TRAN_TRANSACTION_LINES tl ON t.transaction_id = tl.transaction_id
    LEFT JOIN RAW.NETSUITE_5TRAN_ACCOUNTS a
    on tl.ACCOUNT_ID = a.ACCOUNT_ID 
    LEFT JOIN (select * from RAW.NETSUITE_GLAccountNumbers where SourceSystem_ID = 5)  gl
    on a.accountnumber = gl.GLAccountNumber
    where t.transaction_type = 'Sales Order'
    group by t.TRANSACTION_ID , t.TRANID , t.TRANDATE ) totals ON t.transaction_id = totals.transaction_id
--Customer Party ID
LEFT JOIN bo.party p
ON t.entity_id = p.party_identifier
AND p.party_identifier_type = 'NETSUITE_CUSTOMER_ID'
AND p.source_system_id = $source_system_id
--Location Party ID
LEFT JOIN bo.party lp
ON cast(t.location_id as varchar) = lp.party_identifier
AND lp.party_identifier_type = 'NETSUITE_LOCATION_ID'
AND lp.source_system_id = $source_system_id

WHERE t.transaction_type = 'Sales Order') as lso

ON soh.source_system_id = lso.source_system_id
AND soh.netsuite_order_no = lso.netsuite_order_no

WHEN MATCHED THEN UPDATE 
SET 
soh.brand_party_id = lso.brand_party_id,
soh.customer_party_id = lso.customer_party_id,
soh.store_party_id = lso.store_party_id,
soh.bill_to_party_id = lso.bill_to_party_id,
soh.ship_to_party_id = lso.ship_to_party_id,
soh.order_dealer_party_id = lso.order_dealer_party_id,
soh.brand_no = lso.brand_no,
soh.brand_no_type = lso.brand_no_type,
soh.sales_order_no = lso.sales_order_no,
soh.sales_order_no_type = lso.sales_order_no_type,
soh.sales_order_reference_no = lso.sales_order_reference_no,
soh.sfdc_order_no = lso.sfdc_order_no,
soh.sfdc_order_no_type = lso.sfdc_order_no_type,
soh.upstream_sales_order_no = lso.upstream_sales_order_no,
soh.upstream_sales_order_no_type = lso.upstream_sales_order_no_type,
soh.sfdc_table_no = lso.sfdc_table_no,
soh.sfcc_order_no = lso.sfcc_order_no,
soh.salesforce_order_no = lso.salesforce_order_no,
soh.purchase_order_no = lso.purchase_order_no,
soh.imarc_order_no = lso.imarc_order_no,
soh.netsuite_salesorder_no = lso.netsuite_salesorder_no,
soh.customer_no = lso.customer_no,
soh.customer_no_type = lso.customer_no_type,
soh.erp_customer_no = lso.erp_customer_no,
soh.erp_customer_no_type = lso.erp_customer_no_type,
soh.bill_to_customer_no = lso.bill_to_customer_no,
soh.bill_to_customer_no_type = lso.bill_to_customer_no_type,
soh.ship_to_customer_no = lso.ship_to_customer_no,
soh.ship_to_customer_no_type = lso.ship_to_customer_no_type,
soh.netsuite_customer_no = lso.netsuite_customer_no,
soh.order_dealer_account_no = lso.order_dealer_account_no,
soh.sales_rep_no = lso.sales_rep_no,
soh.sales_rep_no_type = lso.sales_rep_no_type,
soh.store_location_no = lso.store_location_no,
soh.store_location_no_type = lso.store_location_no_type,
soh.netsuite_sales_location_no = lso.netsuite_sales_location_no,
soh.order_dealer_no = lso.order_dealer_no,
soh.quote_no = lso.quote_no,
soh.quote_no_type = lso.quote_no_type,
soh.quote_transaction_no = lso.quote_transaction_no,
soh.quote_expiration = lso.quote_expiration,
soh.payment_terms_no = lso.payment_terms_no,
soh.payment_terms_no_type = lso.payment_terms_no_type,
soh.order_line_count = lso.order_line_count,
soh.item_count = lso.item_count,
soh.sale_status = lso.sale_status,
soh.sales_order_status = lso.sales_order_status,
soh.sfdc_status_code = lso.sfdc_status_code,
soh.netsuite_sales_order_status = lso.netsuite_sales_order_status,
soh.netsuite_status = lso.netsuite_status,
soh.email_transaction_no = lso.email_transaction_no,
soh.shipping_method_no = lso.shipping_method_no,
soh.shipping_method_no_type = lso.shipping_method_no_type,
soh.parcel_shipping_method_no = lso.parcel_shipping_method_no,
soh.parcel_shipping_method_no_type = lso.parcel_shipping_method_no_type,
soh.netsuite_shipping_method_no = lso.netsuite_shipping_method_no,
soh.shipping_zone_code = lso.shipping_zone_code,
soh.sales_channel = lso.sales_channel,
soh.customer_source = lso.customer_source,
soh.applied_promotion_no = lso.applied_promotion_no,
soh.promotion_no = lso.promotion_no,
soh.promotion_no_type = lso.promotion_no_type,
soh.discount_percent = lso.discount_percent,
soh.opportunity_project_name = lso.opportunity_project_name,
soh.netsuite_account_source_no = lso.netsuite_account_source_no,
soh.order_currency_code = lso.order_currency_code,
soh.after_discount_amount = lso.after_discount_amount,
soh.custom_amount = lso.custom_amount,
soh.custom_amount_name = lso.custom_amount_name,
soh.discount_amount = lso.discount_amount,
soh.IMARC_discount_amount = lso.IMARC_discount_amount,
soh.margin_amount = lso.margin_amount,
soh.merchandise_amount = lso.merchandise_amount,
soh.net_retail_amount = lso.net_retail_amount,
soh.outstanding_payment_amount = lso.outstanding_payment_amount,
soh.payment_amount = lso.payment_amount,
soh.retail_amount = lso.retail_amount,
soh.sales_order_amount = lso.sales_order_amount,
soh.tax_total_amount = lso.tax_total_amount,
soh.valid_order_payment_amount = lso.valid_order_payment_amount,
soh.shipping_amount = lso.shipping_amount,
soh.tax_amount = lso.tax_amount,
soh.bundled_est_ship_timestamp = lso.bundled_est_ship_timestamp,
soh.est_delivery_max_timestamp = lso.est_delivery_max_timestamp,
soh.est_delivery_min_timestamp = lso.est_delivery_min_timestamp,
soh.est_ship_timestamp = lso.est_ship_timestamp,
soh.payment_request_timestamp = lso.payment_request_timestamp,
soh.sfdc_effective_timestamp = lso.sfdc_effective_timestamp,
soh.sfdc_activated_timestamp = lso.sfdc_activated_timestamp,
soh.sfdc_created_timestamp = lso.sfdc_created_timestamp,
soh.sfdc_last_modified_timestamp = lso.sfdc_last_modified_timestamp,
soh.est_delivery_timestamp = lso.est_delivery_timestamp,
soh.salesorder_placed_timestamp = lso.salesorder_placed_timestamp,
soh.quote_expiration_timestamp = lso.quote_expiration_timestamp,
soh.netsuite_error_code = lso.netsuite_error_code,
soh.resale_template_no = lso.resale_template_no,
soh.sales_order_blob1 = lso.sales_order_blob1,
soh.sales_order_blob1_name = lso.sales_order_blob1_name,
soh.sales_order_blob2 = lso.sales_order_blob2,
soh.sales_order_blob2_name = lso.sales_order_blob2_name,
--soh.created_timestamp = lso.created_timestamp,
soh.updated_timestamp = lso.updated_timestamp,
--soh.created_process = lso.created_process,
soh.updated_process = lso.updated_process,
soh.order_date = lso.order_date,
soh.order_date_type = lso.order_date_type,
soh.netsuite_created_timestamp = lso.netsuite_created_timestamp,
soh.netsuite_last_modified_timestamp = lso.netsuite_last_modified_timestamp,
soh.sales_order_amount_usd = lso.sales_order_amount_usd,
soh.tax_total_amount_usd = lso.tax_total_amount_usd,
soh.shipping_amount_usd = lso.shipping_amount_usd,
soh.netsuite_esd_delta  = lso.netsuite_esd_delta ,
soh.netsuite_approved_date  = lso.netsuite_approved_date ,
soh.netsuite_closed  = lso.netsuite_closed ,
soh.netsuite_created_by_no = lso.netsuite_created_by_no,
soh.netsuite_created_from_no  = lso.netsuite_created_from_no ,
soh.netsuite_currency_no = lso.netsuite_currency_no,
soh.netsuite_email  = lso.netsuite_email ,
soh.netsuite_exchange_rate  = lso.netsuite_exchange_rate ,
soh.netsuite_floor_sale  = lso.netsuite_floor_sale ,
soh.netsuite_global_account  = lso.netsuite_global_account ,
soh.netsuite_is_exchange_order  = lso.netsuite_is_exchange_order ,
soh.netsuite_is_non_posting  = lso.netsuite_is_non_posting ,
soh.netsuite_memo  = lso.netsuite_memo ,
soh.netsuite_order_location_text  = lso.netsuite_order_location_text ,
soh.netsuite_original_estimated_ship_date  = lso.netsuite_original_estimated_ship_date ,
soh.netsuite_original_sales_order_no = lso.netsuite_original_sales_order_no,
soh.netsuite_payment_terms_no  = lso.netsuite_payment_terms_no ,
soh.netsuite_pick_up  = lso.netsuite_pick_up ,
soh.netsuite_pos_status_no  = lso.netsuite_pos_status_no ,
soh.netsuite_promotion_code  = lso.netsuite_promotion_code ,
soh.netsuite_purchase_order_type_no = lso.netsuite_purchase_order_type_no,
soh.netsuite_quote_date  = lso.netsuite_quote_date ,
soh.netsuite_related_tranid  = lso.netsuite_related_tranid ,
soh.netsuite_sales_effective_date  = lso.netsuite_sales_effective_date ,
soh.netsuite_shipaddress  = lso.netsuite_shipaddress ,
soh.netsuite_shipment_received  = lso.netsuite_shipment_received ,
soh.netsuite_shipping_item_no  = lso.netsuite_shipping_item_no ,
soh.netsuite_source_0  = lso.netsuite_source_0 ,
soh.netsuite_split_commission_percent  = lso.netsuite_split_commission_percent ,
soh.netsuite_split_commission_rep_no = lso.netsuite_split_commission_rep_no,
soh.netsuite_transaction_extid  = lso.netsuite_transaction_extid ,
soh.netsuite_transaction_type  = lso.netsuite_transaction_type ,
soh.netsuite_vip_order = lso.netsuite_vip_order,

-- Easter (ET) timestamp fields
soh.quote_expiration_et = lso.quote_expiration_et,
soh.bundled_est_ship_timestamp_et = lso.bundled_est_ship_timestamp_et,
soh.est_delivery_max_timestamp_et = lso.est_delivery_max_timestamp_et,
soh.est_delivery_min_timestamp_et = lso.est_delivery_min_timestamp_et,
soh.est_ship_timestamp_et = lso.est_ship_timestamp_et,
soh.payment_request_timestamp_et = lso.payment_request_timestamp_et,
soh.sfdc_effective_timestamp_et = lso.sfdc_effective_timestamp_et,
soh.sfdc_activated_timestamp_et = lso.sfdc_activated_timestamp_et,
soh.sfdc_created_timestamp_et = lso.sfdc_created_timestamp_et,
soh.sfdc_last_modified_timestamp_et = lso.sfdc_last_modified_timestamp_et,
soh.est_delivery_timestamp_et = lso.est_delivery_timestamp_et,
soh.salesorder_placed_timestamp_et = lso.salesorder_placed_timestamp_et,
soh.quote_expiration_timestamp_et = lso.quote_expiration_timestamp_et,
--soh.created_timestamp_et = lso.created_timestamp_et,
soh.updated_timestamp_et = lso.updated_timestamp_et,
soh.order_date_et = lso.order_date_et,
soh.netsuite_created_timestamp_et = lso.netsuite_created_timestamp_et,
soh.netsuite_last_modified_timestamp_et = lso.netsuite_last_modified_timestamp_et,
soh.netsuite_approved_date_et = lso.netsuite_approved_date_et,
soh.netsuite_closed_et = lso.netsuite_closed_et,
soh.netsuite_original_estimated_ship_date_et = lso.netsuite_original_estimated_ship_date_et,
soh.netsuite_quote_date_et = lso.netsuite_quote_date_et,
soh.netsuite_sales_effective_date_et = lso.netsuite_sales_effective_date_et,
soh.netsuite_shipment_received_et = lso.netsuite_shipment_received_et,

-- UTC timestamp fields
soh.quote_expiration_utc = lso.quote_expiration_utc,
soh.bundled_est_ship_timestamp_utc = lso.bundled_est_ship_timestamp_utc,
soh.est_delivery_max_timestamp_utc = lso.est_delivery_max_timestamp_utc,
soh.est_delivery_min_timestamp_utc = lso.est_delivery_min_timestamp_utc,
soh.est_ship_timestamp_utc = lso.est_ship_timestamp_utc,
soh.payment_request_timestamp_utc = lso.payment_request_timestamp_utc,
soh.sfdc_effective_timestamp_utc = lso.sfdc_effective_timestamp_utc,
soh.sfdc_activated_timestamp_utc = lso.sfdc_activated_timestamp_utc,
soh.sfdc_created_timestamp_utc = lso.sfdc_created_timestamp_utc,
soh.sfdc_last_modified_timestamp_utc = lso.sfdc_last_modified_timestamp_utc,
soh.est_delivery_timestamp_utc = lso.est_delivery_timestamp_utc,
soh.salesorder_placed_timestamp_utc = lso.salesorder_placed_timestamp_utc,
soh.quote_expiration_timestamp_utc = lso.quote_expiration_timestamp_utc,
--soh.created_timestamp_utc = lso.created_timestamp_utc,
soh.updated_timestamp_utc = lso.updated_timestamp_utc,
soh.order_date_utc = lso.order_date_utc,
soh.netsuite_created_timestamp_utc = lso.netsuite_created_timestamp_utc,
soh.netsuite_last_modified_timestamp_utc = lso.netsuite_last_modified_timestamp_utc,
soh.netsuite_approved_date_utc = lso.netsuite_approved_date_utc,
soh.netsuite_closed_utc = lso.netsuite_closed_utc,
soh.netsuite_original_estimated_ship_date_utc = lso.netsuite_original_estimated_ship_date_utc,
soh.netsuite_quote_date_utc = lso.netsuite_quote_date_utc,
soh.netsuite_sales_effective_date_utc = lso.netsuite_sales_effective_date_utc,
soh.netsuite_shipment_received_utc = lso.netsuite_shipment_received_utc,
soh.org_data_source_timezone = lso.org_data_source_timezone,
soh.sales_channel_type = lso.sales_channel_type

WHEN NOT MATCHED THEN INSERT 
(source_system_id,
brand_party_id,
customer_party_id,
store_party_id,
bill_to_party_id,
ship_to_party_id,
order_dealer_party_id,
brand_no,
brand_no_type,
sales_order_no,
sales_order_no_type,
sales_order_reference_no,
sfdc_order_no,
sfdc_order_no_type,
upstream_sales_order_no,
upstream_sales_order_no_type,
sfdc_table_no,
sfcc_order_no,
salesforce_order_no,
purchase_order_no,
netsuite_order_no,
imarc_order_no,
netsuite_salesorder_no,
customer_no,
customer_no_type,
erp_customer_no,
erp_customer_no_type,
bill_to_customer_no,
bill_to_customer_no_type,
ship_to_customer_no,
ship_to_customer_no_type,
netsuite_customer_no,
order_dealer_account_no,
sales_rep_no,
sales_rep_no_type,
store_location_no,
store_location_no_type,
netsuite_sales_location_no,
order_dealer_no,
quote_no,
quote_no_type,
quote_transaction_no,
quote_expiration,
payment_terms_no,
payment_terms_no_type,
order_line_count,
item_count,
sale_status,
sales_order_status,
sfdc_status_code,
netsuite_sales_order_status,
netsuite_status,
email_transaction_no,
shipping_method_no,
shipping_method_no_type,
parcel_shipping_method_no,
parcel_shipping_method_no_type,
netsuite_shipping_method_no,
shipping_zone_code,
sales_channel,
customer_source,
applied_promotion_no,
promotion_no,
promotion_no_type,
discount_percent,
opportunity_project_name,
netsuite_account_source_no,
order_currency_code,
after_discount_amount,
custom_amount,
custom_amount_name,
discount_amount,
IMARC_discount_amount,
margin_amount,
merchandise_amount,
net_retail_amount,
outstanding_payment_amount,
payment_amount,
retail_amount,
sales_order_amount,
tax_total_amount,
valid_order_payment_amount,
shipping_amount,
tax_amount,
bundled_est_ship_timestamp,
est_delivery_max_timestamp,
est_delivery_min_timestamp,
est_ship_timestamp,
payment_request_timestamp,
sfdc_effective_timestamp,
sfdc_activated_timestamp,
sfdc_created_timestamp,
sfdc_last_modified_timestamp,
est_delivery_timestamp,
salesorder_placed_timestamp,
quote_expiration_timestamp,
netsuite_error_code,
resale_template_no,
sales_order_blob1,
sales_order_blob1_name,
sales_order_blob2,
sales_order_blob2_name,
created_timestamp,
updated_timestamp,
created_process,
updated_process,
order_date,
order_date_type,
netsuite_created_timestamp,
netsuite_last_modified_timestamp,
sales_order_amount_usd,
tax_total_amount_usd,
shipping_amount_usd,
netsuite_esd_delta ,
netsuite_approved_date ,
netsuite_closed ,
netsuite_created_by_no,
netsuite_created_from_no ,
netsuite_currency_no,
netsuite_email ,
netsuite_exchange_rate ,
netsuite_floor_sale ,
netsuite_global_account ,
netsuite_is_exchange_order ,
netsuite_is_non_posting ,
netsuite_memo ,
netsuite_order_location_text ,
netsuite_original_estimated_ship_date ,
netsuite_original_sales_order_no,
netsuite_payment_terms_no ,
netsuite_pick_up ,
netsuite_pos_status_no ,
netsuite_promotion_code ,
netsuite_purchase_order_type_no,
netsuite_quote_date ,
netsuite_related_tranid ,
netsuite_sales_effective_date ,
netsuite_shipaddress ,
netsuite_shipment_received ,
netsuite_shipping_item_no ,
netsuite_source_0 ,
netsuite_split_commission_percent ,
netsuite_split_commission_rep_no,
netsuite_transaction_extid ,
netsuite_transaction_type ,
netsuite_vip_order,
-- Easter (ET) timestamp fields
quote_expiration_et,
bundled_est_ship_timestamp_et,
est_delivery_max_timestamp_et,
est_delivery_min_timestamp_et,
est_ship_timestamp_et,
payment_request_timestamp_et,
sfdc_effective_timestamp_et,
sfdc_activated_timestamp_et,
sfdc_created_timestamp_et,
sfdc_last_modified_timestamp_et,
est_delivery_timestamp_et,
salesorder_placed_timestamp_et,
quote_expiration_timestamp_et,
created_timestamp_et,
updated_timestamp_et,
order_date_et,
netsuite_created_timestamp_et,
netsuite_last_modified_timestamp_et,
netsuite_approved_date_et,
netsuite_closed_et,
netsuite_original_estimated_ship_date_et,
netsuite_quote_date_et,
netsuite_sales_effective_date_et,
netsuite_shipment_received_et,
-- UTC timestamp fields
quote_expiration_utc,
bundled_est_ship_timestamp_utc,
est_delivery_max_timestamp_utc,
est_delivery_min_timestamp_utc,
est_ship_timestamp_utc,
payment_request_timestamp_utc,
sfdc_effective_timestamp_utc,
sfdc_activated_timestamp_utc,
sfdc_created_timestamp_utc,
sfdc_last_modified_timestamp_utc,
est_delivery_timestamp_utc,
salesorder_placed_timestamp_utc,
quote_expiration_timestamp_utc,
created_timestamp_utc,
updated_timestamp_utc,
order_date_utc,
netsuite_created_timestamp_utc,
netsuite_last_modified_timestamp_utc,
netsuite_approved_date_utc,
netsuite_closed_utc,
netsuite_original_estimated_ship_date_utc,
netsuite_quote_date_utc,
netsuite_sales_effective_date_utc,
netsuite_shipment_received_utc,
org_data_source_timezone,
sales_channel_type) 

VALUES 
(lso.source_system_id,
lso.brand_party_id,
lso.customer_party_id,
lso.store_party_id,
lso.bill_to_party_id,
lso.ship_to_party_id,
lso.order_dealer_party_id,
lso.brand_no,
lso.brand_no_type,
lso.sales_order_no,
lso.sales_order_no_type,
lso.sales_order_reference_no,
lso.sfdc_order_no,
lso.sfdc_order_no_type,
lso.upstream_sales_order_no,
lso.upstream_sales_order_no_type,
lso.sfdc_table_no,
lso.sfcc_order_no,
lso.salesforce_order_no,
lso.purchase_order_no,
lso.netsuite_order_no,
lso.imarc_order_no,
lso.netsuite_salesorder_no,
lso.customer_no,
lso.customer_no_type,
lso.erp_customer_no,
lso.erp_customer_no_type,
lso.bill_to_customer_no,
lso.bill_to_customer_no_type,
lso.ship_to_customer_no,
lso.ship_to_customer_no_type,
lso.netsuite_customer_no,
lso.order_dealer_account_no,
lso.sales_rep_no,
lso.sales_rep_no_type,
lso.store_location_no,
lso.store_location_no_type,
lso.netsuite_sales_location_no,
lso.order_dealer_no,
lso.quote_no,
lso.quote_no_type,
lso.quote_transaction_no,
lso.quote_expiration,
lso.payment_terms_no,
lso.payment_terms_no_type,
lso.order_line_count,
lso.item_count,
lso.sale_status,
lso.sales_order_status,
lso.sfdc_status_code,
lso.netsuite_sales_order_status,
lso.netsuite_status,
lso.email_transaction_no,
lso.shipping_method_no,
lso.shipping_method_no_type,
lso.parcel_shipping_method_no,
lso.parcel_shipping_method_no_type,
lso.netsuite_shipping_method_no,
lso.shipping_zone_code,
lso.sales_channel,
lso.customer_source,
lso.applied_promotion_no,
lso.promotion_no,
lso.promotion_no_type,
lso.discount_percent,
lso.opportunity_project_name,
lso.netsuite_account_source_no,
lso.order_currency_code,
lso.after_discount_amount,
lso.custom_amount,
lso.custom_amount_name,
lso.discount_amount,
lso.IMARC_discount_amount,
lso.margin_amount,
lso.merchandise_amount,
lso.net_retail_amount,
lso.outstanding_payment_amount,
lso.payment_amount,
lso.retail_amount,
lso.sales_order_amount,
lso.tax_total_amount,
lso.valid_order_payment_amount,
lso.shipping_amount,
lso.tax_amount,
lso.bundled_est_ship_timestamp,
lso.est_delivery_max_timestamp,
lso.est_delivery_min_timestamp,
lso.est_ship_timestamp,
lso.payment_request_timestamp,
lso.sfdc_effective_timestamp,
lso.sfdc_activated_timestamp,
lso.sfdc_created_timestamp,
lso.sfdc_last_modified_timestamp,
lso.est_delivery_timestamp,
lso.salesorder_placed_timestamp,
lso.quote_expiration_timestamp,
lso.netsuite_error_code,
lso.resale_template_no,
lso.sales_order_blob1,
lso.sales_order_blob1_name,
lso.sales_order_blob2,
lso.sales_order_blob2_name,
lso.created_timestamp,
lso.updated_timestamp,
lso.created_process,
lso.updated_process,
lso.order_date,
lso.order_date_type,
lso.netsuite_created_timestamp,
lso.netsuite_last_modified_timestamp,
lso.sales_order_amount_usd,
lso.tax_total_amount_usd,
lso.shipping_amount_usd,
lso.netsuite_esd_delta ,
lso.netsuite_approved_date ,
lso.netsuite_closed ,
lso.netsuite_created_by_no,
lso.netsuite_created_from_no ,
lso.netsuite_currency_no,
lso.netsuite_email ,
lso.netsuite_exchange_rate ,
lso.netsuite_floor_sale ,
lso.netsuite_global_account ,
lso.netsuite_is_exchange_order ,
lso.netsuite_is_non_posting ,
lso.netsuite_memo ,
lso.netsuite_order_location_text ,
lso.netsuite_original_estimated_ship_date ,
lso.netsuite_original_sales_order_no,
lso.netsuite_payment_terms_no ,
lso.netsuite_pick_up ,
lso.netsuite_pos_status_no ,
lso.netsuite_promotion_code ,
lso.netsuite_purchase_order_type_no,
lso.netsuite_quote_date ,
lso.netsuite_related_tranid ,
lso.netsuite_sales_effective_date ,
lso.netsuite_shipaddress ,
lso.netsuite_shipment_received ,
lso.netsuite_shipping_item_no ,
lso.netsuite_source_0 ,
lso.netsuite_split_commission_percent ,
lso.netsuite_split_commission_rep_no,
lso.netsuite_transaction_extid ,
lso.netsuite_transaction_type ,
lso.netsuite_vip_order,
-- Easter (ET) timestamp fields
lso.quote_expiration_et,
lso.bundled_est_ship_timestamp_et,
lso.est_delivery_max_timestamp_et,
lso.est_delivery_min_timestamp_et,
lso.est_ship_timestamp_et,
lso.payment_request_timestamp_et,
lso.sfdc_effective_timestamp_et,
lso.sfdc_activated_timestamp_et,
lso.sfdc_created_timestamp_et,
lso.sfdc_last_modified_timestamp_et,
lso.est_delivery_timestamp_et,
lso.salesorder_placed_timestamp_et,
lso.quote_expiration_timestamp_et,
lso.created_timestamp_et,
lso.updated_timestamp_et,
lso.order_date_et,
lso.netsuite_created_timestamp_et,
lso.netsuite_last_modified_timestamp_et,
lso.netsuite_approved_date_et,
lso.netsuite_closed_et,
lso.netsuite_original_estimated_ship_date_et,
lso.netsuite_quote_date_et,
lso.netsuite_sales_effective_date_et,
lso.netsuite_shipment_received_et,
-- UTC timestamp fields
lso.quote_expiration_utc,
lso.bundled_est_ship_timestamp_utc,
lso.est_delivery_max_timestamp_utc,
lso.est_delivery_min_timestamp_utc,
lso.est_ship_timestamp_utc,
lso.payment_request_timestamp_utc,
lso.sfdc_effective_timestamp_utc,
lso.sfdc_activated_timestamp_utc,
lso.sfdc_created_timestamp_utc,
lso.sfdc_last_modified_timestamp_utc,
lso.est_delivery_timestamp_utc,
lso.salesorder_placed_timestamp_utc,
lso.quote_expiration_timestamp_utc,
lso.created_timestamp_utc,
lso.updated_timestamp_utc,
lso.order_date_utc,
lso.netsuite_created_timestamp_utc,
lso.netsuite_last_modified_timestamp_utc,
lso.netsuite_approved_date_utc,
lso.netsuite_closed_utc,
lso.netsuite_original_estimated_ship_date_utc,
lso.netsuite_quote_date_utc,
lso.netsuite_sales_effective_date_utc,
lso.netsuite_shipment_received_utc,
lso.org_data_source_timezone,
lso.sales_channel_type
);



---------------------------------------------
-- SALES ORDER LINE ------------------------
---------------------------------------------

MERGE INTO bo.sales_order_line as sol USING (
SELECT
$source_system_id as source_system_id,
ANY_VALUE(tl.AMOUNT * -1) as sales_order_amount,
ANY_VALUE(tl.AMOUNT * -1 * t.EXCHANGE_RATE) as sales_order_amount_usd,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.DATE_LAST_MODIFIED)) as netsuite_last_modified_timestamp,
ANY_VALUE(convert_timezone('America/Detroit', tl.DATE_LAST_MODIFIED)) as netsuite_last_modified_timestamp_et,
ANY_VALUE(convert_timezone('UTC', tl.DATE_LAST_MODIFIED)) as netsuite_last_modified_timestamp_utc,
ANY_VALUE(tl.ITEM_COUNT * -1) as item_count,
ANY_VALUE(cast(tl.ITEM_ID as varchar)) as item_no,
ANY_VALUE('netsuite_item_id') as item_no_type,
ANY_VALUE(ITEM_UNIT_PRICE) as item_unit_price,
ANY_VALUE(TO_VARCHAR(t.LOCATION_ID)) as netsuite_sales_location_no,
ANY_VALUE(lp.party_id) as store_party_id,
ANY_VALUE(tl.MEMO) as memo,
ANY_VALUE(tl.QUANTITY_RECEIVED_IN_SHIPMENT) as quantity_received_in_shipment,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.SHIPDATE)) as shipdate,
TO_VARCHAR(t.TRANSACTION_ID) as netsuite_order_no,
tl.TRANSACTION_LINE_ID as sales_order_line_no,
ANY_VALUE(t.TRANID) as sales_order_no,
ANY_VALUE('netsuite_tranid') as sales_order_no_type,
ANY_VALUE(tl.ACCOUNT_ID) as netsuite_account_no,
ANY_VALUE(a.accountnumber) as netsuite_gl_account_no,
ANY_VALUE(gl.AccountType) as gl_revenue_category,
ANY_VALUE(tl.CANCELLED_QUANTITY) as cancelled_quantity,
ANY_VALUE(tl.COMMISSIONABLE_SHIPPING_CHARG) as commissionable_shipping_charge,
ANY_VALUE(tl.COST_ESTIMATE_TYPE) as cost_estimate_type,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.CREATED_DATE))  as netsuite_created_timestamp,
ANY_VALUE(convert_timezone('America/Detroit', tl.CREATED_DATE)) as netsuite_created_timestamp_et,
ANY_VALUE(convert_timezone('UTC', tl.CREATED_DATE)) as netsuite_created_timestamp_utc,
ANY_VALUE(tl.DEPARTMENT_ID) as netsuite_department_no,
ANY_VALUE(tl.DWR_CUSTOM_SHIP_TO_ADDRESS) as netsuite_dwr_custom_ship_to_address,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.ESTIMATED_SHIP_DATE)) as netsuite_estimated_item_ship_date,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.FUTURE_SHIP_DATE)) as netsuite_future_ship_date,
ANY_VALUE(tl.GROSS_AMOUNT * -1) as order_gross_dollar_amount,
ANY_VALUE(tl.GROSS_AMOUNT * -1 * t.EXCHANGE_RATE) as order_gross_dollar_amount_usd,
ANY_VALUE(tl.HARMONIZED_CODE) as netsuite_harmonized_code,
ANY_VALUE(tl.ISTAXABLE) as istaxable,
ANY_VALUE(tl.ITEM_COST) as item_cost,
ANY_VALUE(tl.ITEM_COST * t.EXCHANGE_RATE) as item_cost_usd,
ANY_VALUE(c.SYMBOL) as order_currency_code,
ANY_VALUE(tl.ITEM_RECEIVED) as item_received,
ANY_VALUE(tl.ITEM_STATUS) as item_status,
ANY_VALUE(tl.NET_AMOUNT * -1) as order_net_dollar_amount,
ANY_VALUE(tl.NET_AMOUNT * -1 * t.EXCHANGE_RATE) as order_net_dollar_amount_usd,
ANY_VALUE(tl.ORIGINAL_QUANTITY) as original_quantity,
ANY_VALUE(tl.PAYMENT_METHOD_ID) as netsuite_payment_method_no,
ANY_VALUE(tl.PRICE_OVERRIDE_REASON) as price_override_reason,
ANY_VALUE(tl.PRICE_TYPE_ID) as netsuite_price_type_no,
ANY_VALUE(tl.REASON_CODE_ID) as netsuite_reason_code_no,
ANY_VALUE(tl.RETAIL_AT_TIME_OF_ORDER) as retail_at_time_of_order,
ANY_VALUE(tl.RETAIL_AT_TIME_OF_ORDER * t.EXCHANGE_RATE) as retail_at_time_of_order_usd,
ANY_VALUE(tl.SENT_TO_WMS) as netsuite_sent_to_wms,
ANY_VALUE(tl.SHIP_OVERRIDE_REASON) as ship_override_reason,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.SHIPMENT_RECEIVED)) as shipment_received_date,
ANY_VALUE(tl.SHIPPING_AMOUNT) as shipping_amount,
ANY_VALUE(tl.SHIPPING_METHOD) as shipping_method,
ANY_VALUE(tl.SHIPPING_REFUND) as shipping_refund,
ANY_VALUE(tl.STATUS) as status,
ANY_VALUE(tl.TAX_AMOUNT) as order_tax_amount,
ANY_VALUE(tl.NON_POSTING_LINE) as netsuite_non_posting_line,
ANY_VALUE(tl.CUSTOMER_SERVICE_HOLD) as customer_service_hold,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.DATE_CLOSED)) as date_closed_timestamp,
ANY_VALUE(convert_timezone('America/Detroit', tl.DATE_CLOSED)) as date_closed_timestamp_et,
ANY_VALUE(convert_timezone('UTC', tl.DATE_CLOSED)) as date_closed_timestamp_utc,
ANY_VALUE(tl.QTY_CANCELED_IN_SCALE) as qty_canceled_in_scale,
ANY_VALUE(tl.QTY_SENT_TO_SCALE) as qty_sent_to_scale,
ANY_VALUE(tl.QUANTITY_COMMITTED) as quantity_committed,
ANY_VALUE(tl.PHONE_NUMBER) as customer_phone_number,
ANY_VALUE(tl.LINE_UNIQUE_KEY) as netsuite_line_unique_key,
ANY_VALUE(tl.SHIPTOGETHER_GROUP) as shiptogether_group,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.CALCULATED_HOLD_TO_SHIP_DATE)) as calculated_hold_to_ship_date,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.ORIGINAL_ESTIMATED_SHIP_DATE)) as original_estimated_ship_date,
ANY_VALUE(TO_TIMESTAMP_NTZ(tl.AVAILABLE_TO_SHIP_DATE)) as available_to_ship_date,
ANY_VALUE(current_timestamp) as created_timestamp,
ANY_VALUE(current_timestamp) as updated_timestamp,
ANY_VALUE('sales_order_line_load') as created_process,
ANY_VALUE('sales_order_line_update') as updated_process,
ANY_VALUE('America/Los_Angeles') as source_timezone
FROM
RAW.NETSUITE_5TRAN_TRANSACTIONS t
INNER JOIN RAW.NETSUITE_5TRAN_CURRENCIES c ON t.currency_id = c.currency_id
INNER JOIN RAW.NETSUITE_5TRAN_TRANSACTION_LINES tl ON t.transaction_id = tl.transaction_id
LEFT JOIN bo.party lp ON cast(tl.location_id as varchar) = lp.party_identifier AND lp.party_identifier_type = 'NETSUITE_LOCATION_ID'
LEFT JOIN RAW.NETSUITE_5TRAN_ACCOUNTS a on tl.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN (select * from RAW.NETSUITE_GLAccountNumbers where SourceSystem_ID = 5)  gl on a.accountnumber = gl.GLAccountNumber
WHERE t.transaction_type = 'Sales Order'
GROUP BY t.transaction_id, tl.transaction_line_id) solt

ON  sol.netsuite_order_no = solt.netsuite_order_no AND
    sol.sales_order_line_no = solt.sales_order_line_no AND
    sol.source_system_id = solt.source_system_id


WHEN MATCHED THEN UPDATE
SET
--sol.source_system_id = solt.source_system_id,
sol.sales_order_amount = solt.sales_order_amount,
sol.sales_order_amount_usd = solt.sales_order_amount_usd,
sol.netsuite_last_modified_timestamp = solt.netsuite_last_modified_timestamp,
sol.netsuite_last_modified_timestamp_et = solt.netsuite_last_modified_timestamp_et,
sol.netsuite_last_modified_timestamp_utc = solt.netsuite_last_modified_timestamp_utc,
sol.item_count = solt.item_count,
sol.item_no = solt.item_no,
sol.item_no_type = solt.item_no_type,
sol.item_unit_price = solt.item_unit_price,
sol.netsuite_sales_location_no = solt.netsuite_sales_location_no,
sol.store_party_id = solt.store_party_id,
sol.memo = solt.memo,
sol.quantity_received_in_shipment = solt.quantity_received_in_shipment,
sol.shipdate = solt.shipdate,
--sol.netsuite_order_no = solt.netsuite_order_no,
--sol.sales_order_line_no = solt.sales_order_line_no,
sol.sales_order_no = solt.sales_order_no,
sol.sales_order_no_type = solt.sales_order_no_type,
sol.netsuite_account_no = solt.netsuite_account_no,
sol.netsuite_gl_account_no = solt.netsuite_gl_account_no,
sol.gl_revenue_category = solt.gl_revenue_category,
sol.cancelled_quantity = solt.cancelled_quantity,
sol.commissionable_shipping_charge = solt.commissionable_shipping_charge,
sol.cost_estimate_type = solt.cost_estimate_type,
sol.netsuite_created_timestamp = solt.netsuite_created_timestamp,
sol.netsuite_created_timestamp_et = solt.netsuite_created_timestamp_et,
sol.netsuite_created_timestamp_utc = solt.netsuite_created_timestamp_utc,
sol.netsuite_department_no = solt.netsuite_department_no,
sol.netsuite_dwr_custom_ship_to_address = solt.netsuite_dwr_custom_ship_to_address,
sol.netsuite_estimated_item_ship_date = solt.netsuite_estimated_item_ship_date,
sol.netsuite_future_ship_date = solt.netsuite_future_ship_date,
sol.order_gross_dollar_amount = solt.order_gross_dollar_amount,
sol.order_gross_dollar_amount_usd = solt.order_gross_dollar_amount_usd,
sol.netsuite_harmonized_code = solt.netsuite_harmonized_code,
sol.istaxable = solt.istaxable,
sol.item_cost = solt.item_cost,
sol.item_cost_usd = solt.item_cost_usd,
sol.order_currency_code = solt.order_currency_code,
sol.item_received = solt.item_received,
sol.item_status = solt.item_status,
sol.order_net_dollar_amount = solt.order_net_dollar_amount,
sol.order_net_dollar_amount_usd = solt.order_net_dollar_amount_usd,
sol.original_quantity = solt.original_quantity,
sol.netsuite_payment_method_no = solt.netsuite_payment_method_no,
sol.price_override_reason = solt.price_override_reason,
sol.netsuite_price_type_no = solt.netsuite_price_type_no,
sol.netsuite_reason_code_no = solt.netsuite_reason_code_no,
sol.retail_at_time_of_order = solt.retail_at_time_of_order,
sol.retail_at_time_of_order_usd = solt.retail_at_time_of_order_usd,
sol.netsuite_sent_to_wms = solt.netsuite_sent_to_wms,
sol.ship_override_reason = solt.ship_override_reason,
sol.shipment_received_date = solt.shipment_received_date,
sol.shipping_amount = solt.shipping_amount,
sol.shipping_method = solt.shipping_method,
sol.shipping_refund = solt.shipping_refund,
sol.status = solt.status,
sol.order_tax_amount = solt.order_tax_amount,
sol.netsuite_non_posting_line = solt.netsuite_non_posting_line,
sol.customer_service_hold = solt.customer_service_hold,
sol.date_closed_timestamp = solt.date_closed_timestamp,
sol.date_closed_timestamp_et = solt.date_closed_timestamp_et,
sol.date_closed_timestamp_utc = solt.date_closed_timestamp_utc,
sol.qty_canceled_in_scale = solt.qty_canceled_in_scale,
sol.qty_sent_to_scale = solt.qty_sent_to_scale,
sol.quantity_committed = solt.quantity_committed,
sol.customer_phone_number = solt.customer_phone_number,
sol.netsuite_line_unique_key = solt.netsuite_line_unique_key,
sol.shiptogether_group = solt.shiptogether_group,
sol.calculated_hold_to_ship_date = solt.calculated_hold_to_ship_date,
sol.original_estimated_ship_date = solt.original_estimated_ship_date,
sol.available_to_ship_date = solt.available_to_ship_date,
--sol.created_timestamp = solt.created_timestamp,
sol.updated_timestamp = solt.updated_timestamp,
sol.created_process = solt.created_process,
sol.updated_process = solt.updated_process,
sol.source_timezone = solt.source_timezone

WHEN NOT MATCHED THEN INSERT
(
source_system_id,
sales_order_amount,
sales_order_amount_usd,
netsuite_last_modified_timestamp,
netsuite_last_modified_timestamp_et,
netsuite_last_modified_timestamp_utc,
item_count,
item_no,
item_no_type,
item_unit_price,
netsuite_sales_location_no,
store_party_id,
memo,
quantity_received_in_shipment,
shipdate,
netsuite_order_no,
sales_order_line_no,
sales_order_no,
sales_order_no_type,
netsuite_account_no,
netsuite_gl_account_no,
gl_revenue_category,
cancelled_quantity,
commissionable_shipping_charge,
cost_estimate_type,
netsuite_created_timestamp,
netsuite_created_timestamp_et,
netsuite_created_timestamp_utc,
netsuite_department_no,
netsuite_dwr_custom_ship_to_address,
netsuite_estimated_item_ship_date,
netsuite_future_ship_date,
order_gross_dollar_amount,
order_gross_dollar_amount_usd,
netsuite_harmonized_code,
istaxable,
item_cost,
item_cost_usd,
order_currency_code,
item_received,
item_status,
order_net_dollar_amount,
order_net_dollar_amount_usd,
original_quantity,
netsuite_payment_method_no,
price_override_reason,
netsuite_price_type_no,
netsuite_reason_code_no,
retail_at_time_of_order,
retail_at_time_of_order_usd,
netsuite_sent_to_wms,
ship_override_reason,
shipment_received_date,
shipping_amount,
shipping_method,
shipping_refund,
status,
order_tax_amount,
netsuite_non_posting_line,
customer_service_hold,
date_closed_timestamp,
date_closed_timestamp_et,
date_closed_timestamp_utc,
qty_canceled_in_scale,
qty_sent_to_scale,
quantity_committed,
customer_phone_number,
netsuite_line_unique_key,
shiptogether_group,
calculated_hold_to_ship_date,
original_estimated_ship_date,
available_to_ship_date,
created_timestamp,
updated_timestamp,
created_process,
updated_process,
source_timezone
)
VALUES
(
solt.source_system_id,
solt.sales_order_amount,
solt.sales_order_amount_usd,
solt.netsuite_last_modified_timestamp,
solt.netsuite_last_modified_timestamp_et,
solt.netsuite_last_modified_timestamp_utc,
solt.item_count,
solt.item_no,
solt.item_no_type,
solt.item_unit_price,
solt.netsuite_sales_location_no,
solt.store_party_id,
solt.memo,
solt.quantity_received_in_shipment,
solt.shipdate,
solt.netsuite_order_no,
solt.sales_order_line_no,
solt.sales_order_no,
solt.sales_order_no_type,
solt.netsuite_account_no,
solt.netsuite_gl_account_no,
solt.gl_revenue_category,
solt.cancelled_quantity,
solt.commissionable_shipping_charge,
solt.cost_estimate_type,
solt.netsuite_created_timestamp,
solt.netsuite_created_timestamp_et,
solt.netsuite_created_timestamp_utc,
solt.netsuite_department_no,
solt.netsuite_dwr_custom_ship_to_address,
solt.netsuite_estimated_item_ship_date,
solt.netsuite_future_ship_date,
solt.order_gross_dollar_amount,
solt.order_gross_dollar_amount_usd,
solt.netsuite_harmonized_code,
solt.istaxable,
solt.item_cost,
solt.item_cost_usd,
solt.order_currency_code,
solt.item_received,
solt.item_status,
solt.order_net_dollar_amount,
solt.order_net_dollar_amount_usd,
solt.original_quantity,
solt.netsuite_payment_method_no,
solt.price_override_reason,
solt.netsuite_price_type_no,
solt.netsuite_reason_code_no,
solt.retail_at_time_of_order,
solt.retail_at_time_of_order_usd,
solt.netsuite_sent_to_wms,
solt.ship_override_reason,
solt.shipment_received_date,
solt.shipping_amount,
solt.shipping_method,
solt.shipping_refund,
solt.status,
solt.order_tax_amount,
solt.netsuite_non_posting_line,
solt.customer_service_hold,
solt.date_closed_timestamp,
solt.date_closed_timestamp_et,
solt.date_closed_timestamp_utc,
solt.qty_canceled_in_scale,
solt.qty_sent_to_scale,
solt.quantity_committed,
solt.customer_phone_number,
solt.netsuite_line_unique_key,
solt.shiptogether_group,
solt.calculated_hold_to_ship_date,
solt.original_estimated_ship_date,
solt.available_to_ship_date,
solt.created_timestamp,
solt.updated_timestamp,
solt.created_process,
solt.updated_process,
solt.source_timezone
);
