CREATE TABLE "ENGAGEMENT_EVENT" (
  "ENGAGEMENT_EVENT_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "STIMULUS_VALUE_ID" NUMBER,
  "CONTACT_ID" NUMBER,
  "CONTACT_VALUE" VARCHAR,
  "VENDOR_ADDRESS_NO" VARCHAR,
  "EVENT_LIST_NO" VARCHAR,
  "EVENT_BATCH_NO" VARCHAR,
  "EVENT_TYPE_ID" NUMBER,
  "EVENT_TYPE" VARCHAR,
  "EVENT_TRIGGER_NO" VARCHAR,
  "EVENT_TIMESTAMP" TIMESTAMP_TZ,
  "VENDOR_EVENT_TYPE" VARCHAR,
  "EVENT_COUNT" NUMBER,
  "EVENT_COST" NUMBER,
  "EVENT_DURATION" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "CONTENT" (
  "CONTENT_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CONTENT_TYPE_ID" NUMBER,
  "CONTENT_VALUE" VARCHAR,
  "VENDOR_CONTENT_NO" VARCHAR,
  "VENDOR_FIELD_NAME" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "CONTENT_STIMULUS_EVELOPE_XREF" (
  "CONTENT_ID" NUMBER,
  "STIMULUS_ENVELOPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "RESPONSE_EVENT" (
  "RESPONSE_EVENT_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "STIMULUS_VALUE_ID" NUMBER,
  "CONTACT_ID" NUMBER,
  "CONTACT_VALUE" VARCHAR,
  "VENDOR_ADDRESS_NO" VARCHAR,
  "EVENT_LIST_NO" VARCHAR,
  "EVENT_BATCH_NO" VARCHAR,
  "EVENT_TYPE_ID" NUMBER,
  "EVENT_TYPE" VARCHAR,
  "EVENT_TRIGGER_NO" VARCHAR,
  "EVENT_TIMESTAMP" TIMESTAMP_TZ,
  "VENDOR_EVENT_TYPE" VARCHAR,
  "EVENT_COUNT" NUMBER,
  "EVENT_REVENUE" NUMBER,
  "EVENT_COST" NUMBER,
  "EVENT_DURATION" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "CONTENT_RESPONSE_XREF" (
  "CONTENT_ID" NUMBER,
  "RESPONSE_EVENT_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_CONTENT_RESPONSE_XREF.RESPONSE_EVENT_ID"
    FOREIGN KEY ("RESPONSE_EVENT_ID")
      REFERENCES "RESPONSE_EVENT"("RESPONSE_EVENT_ID")
);

CREATE TABLE "CONTENT_TYPE" (
  "CONTENT_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CONTENT_TYPE" VARCHAR,
  "CONTENT_SUPERTYPE" VARCHAR,
  "CONTENT_SUBTYPE" VARCHAR,
  "VENDOR_CONTENT_TYPE" VARCHAR,
  "VENDOR_FIELD_NAME" VARCHAR,
  "VENDOR_CONTENT_TYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "VALUE_TYPE" (
  "VALUE_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "VALUE_TYPE" VARCHAR,
  "VALUE_SUPERTYPE" VARCHAR,
  "\VALUE_SUBTYPE" VARCHAR,
  "VENDOR_VALUE_TYPE" VARCHAR,
  "VENDOR_VALUE_NAME" VARCHAR,
  "VENDOR_VALUE_NO" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "STIMULUS_VALUE" (
  "STIMULUS_VALUE_ID" NUMBER,
  "STIMULUS_ENVELOPE_ID" NUMBER,
  "STIMULUS_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "VALUE_OWNER_ORGANIZATION_ID" VARCHAR,
  "VALUE_OWNER_PERSON_ID" NUMBER,
  "VALUE_OWNER_ORGANIZATION_NAME" VARCHAR,
  "VALUE_OWNER_PERSON_NAME" VARCHAR,
  "VALUE_ACCOUNT_NO" VARCHAR,
  "VALUE_ACCOUNT_NAME" VARCHAR,
  "VALUE_PROGRAM_NAME" VARCHAR,
  "VALUE_PROGRAM_DESC" VARCHAR,
  "VALUE_PROJECT_NAME" VARCHAR,
  "VALUE_CAMPAIGN_HIERARCHY_ID" NUMBER,
  "VALUE_STATUS" VARCHAR,
  "VENDOR_OWNER_NAME" VARCHAR,
  "VENDOR_PROGRAM_NAME" VARCHAR,
  "VENDOR_PROGRAM_DESC" VARCHAR,
  "VENDOR_PROJECT_NAME" VARCHAR,
  "VENDOR_STATUS" VARCHAR,
  "VALUE_TRIGGER_NO" VARCHAR,
  "VALUE_SCHEME_NO" VARCHAR,
  "VALUE_BATCH_NO" VARCHAR,
  "VALUE_SCHEDULED_TIMESTAMP" TIMESTAMP_TZ,
  "VALUE_ACTUAL_TIMESTAMP" TIMESTAMP_TZ,
  "VALUE_TYPE_ID" NUMBER,
  "VALUE_TYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_STIMULUS_VALUE.VALUE_TYPE_ID"
    FOREIGN KEY ("VALUE_TYPE_ID")
      REFERENCES "VALUE_TYPE"("VALUE_TYPE_ID")
);

CREATE TABLE "CONTENT_STIMULUS_VALUE_XREF" (
  "CONTENT_ID" NUMBER,
  "STIMULUS_VALUE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_CONTENT_STIMULUS_VALUE_XREF.STIMULUS_VALUE_ID"
    FOREIGN KEY ("STIMULUS_VALUE_ID")
      REFERENCES "STIMULUS_VALUE"("STIMULUS_VALUE_ID")
);

CREATE TABLE "ENVELOPE_TYPE" (
  "ENVELOPE_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "ENVELOPE_TYPE" VARCHAR,
  "ENVELOPE_SUPERTYPE" VARCHAR,
  "ENVELOPE_SUBTYPE" VARCHAR,
  "VENDOR_ENVELOPE_TYPE" VARCHAR,
  "VENDOR_ENVELOPE_NAME" VARCHAR,
  "VENDOR_ENVELOPE_NO" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "EVENT_TYPE" (
  "EVENT_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "EVENT_TYPE" VARCHAR,
  "EVENT_SUPERTYPE" VARCHAR,
  "EVENT_SUBTYPE" VARCHAR,
  "VENDOR_EVENT_TYPE" VARCHAR,
  "VENDOR_EVENT_NAME" VARCHAR,
  "VENDOR_EVENT_NO" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "DATASET" (
  "DATASET_ID" NUMBER,
  "DATASET_OWNER_ID" NUMBER,
  "DATASET_OWNER_NAME" VARCHAR,
  "DATASET_NAME" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

CREATE TABLE "STIMULUS_TYPE" (
  "STIMULUS_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "STIMULUS_TYPE" VARCHAR,
  "STIMULUS_SUPERTYPE" VARCHAR,
  "STIMULUS_SUBTYPE" VARCHAR,
  "VENDOR_STIMULUS_TYPE" VARCHAR,
  "VENDOR_STIMULUS_NAME" VARCHAR,
  "VENDOR_STIMULUS_NO" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "STIMULUS" (
  "STIMULUS_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "STIMULUS_OWNER_ORGANIZATION_ID" NUMBER,
  "STIMULUS_OWNER_PERSON_ID" NUMBER,
  "STIMULUS_OWNER_ORGANIZATION_NAME" VARCHAR,
  "STIMULUS_OWNER_PERSON_NAME" VARCHAR,
  "STIMULUS_ACCOUNT_NO" VARCHAR,
  "STIMULUS_ACCOUNT_NAME" VARCHAR,
  "STIMULUS_PROGRAM_NAME" VARCHAR,
  "STIMULUS_PROGRAM_DESC" VARCHAR,
  "STIMULUS_PROJECT_NAME" VARCHAR,
  "STIMULUS_CAMPAIGN_HIERARCHY_ID" NUMBER,
  "STIMULUS_STATUS" VARCHAR,
  "VENDOR_OWNER_NAME" VARCHAR,
  "VENDOR_PROGRAM_NAME" VARCHAR,
  "VENDOR_PROGRAM_DESC" VARCHAR,
  "VENDOR_PROJECT_NAME" VARCHAR,
  "VENDOR_STATUS" VARCHAR,
  "STIMULUS_TRIGGER_NO" VARCHAR,
  "STIMULUS_SCHEME_NO" VARCHAR,
  "STIMULUS_BATCH_NO" VARCHAR,
  "STIMULUS_SCHEDULED_TIMESTAMP" TIMESTAMP_TZ,
  "STIMULUS_ACTUAL_TIMESTAMP" TIMESTAMP_TZ,
  "STIMULUS_START_TIMESTAMP" TIMESTAMP_TZ,
  "STIMULUS_END_TIMESTAMP" TIMESTAMP_TZ,
  "STIMULUS_TYPE_ID" NUMBER,
  "STIMULUS_TYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_STIMULUS.STIMULUS_TYPE_ID"
    FOREIGN KEY ("STIMULUS_TYPE_ID")
      REFERENCES "STIMULUS_TYPE"("STIMULUS_TYPE_ID")
);

CREATE TABLE "STIMULUS_ENVELOPE" (
  "STIMULUS_ENVELOPE_ID" NUMBER,
  "PARENT_STIMULUS_ENVELOPE_ID" NUMBER,
  "STIMULUS_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "ENVELOPE_OWNER_ORGANIZATION_ID" VARCHAR,
  "ENVELOPE_OWNER_PERSON_ID" NUMBER,
  "ENVELOPE_OWNER_ORGANIZATION_NAME" VARCHAR,
  "ENVELOPE_OWNER_PERSON_NAME" VARCHAR,
  "ENVELOPE_ACCOUNT_NO" VARCHAR,
  "ENVELOPE_ACCOUNT_NAME" VARCHAR,
  "ENVELOPE_PROGRAM_NAME" VARCHAR,
  "ENVELOPE_PROGRAM_DESC" VARCHAR,
  "ENVELOPE_PROJECT_NAME" VARCHAR,
  "ENVELOPE_CAMPAIGN_HIERARCHY_ID" NUMBER,
  "ENVELOPE_STATUS" VARCHAR,
  "VENDOR_OWNER_NAME" VARCHAR,
  "VENDOR_PROGRAM_NAME" VARCHAR,
  "VENDOR_PROGRAM_DESC" VARCHAR,
  "VENDOR_PROJECT_NAME" VARCHAR,
  "VENDOR_STATUS" VARCHAR,
  "ENVELOPE_TRIGGER_NO" VARCHAR,
  "ENVELOPE_SCHEME_NO" VARCHAR,
  "ENVELOPE_BATCH_NO" VARCHAR,
  "ENVELOPE_SCHEDULED_TIMESTAMP" TIMESTAMP_TZ,
  "ENVELOPE_ACTUAL_TIMESTAMP" TIMESTAMP_TZ,
  "ENVELOPE_TYPE_ID" NUMBER,
  "ENVELOPE_TYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_STIMULUS_ENVELOPE.ENVELOPE_TYPE_ID"
    FOREIGN KEY ("ENVELOPE_TYPE_ID")
      REFERENCES "ENVELOPE_TYPE"("ENVELOPE_TYPE_ID")
);

CREATE TABLE "CAMPAIGN_HIERARCHY" (
  "CAMPAIGN_HIERARCHY_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "STIMULUS_TYPE" VARCHAR,
  "ENVELOPE_TYPE" VARCHAR,
  "VALUE_TYPE" VARCHAR,
  "CATEGORY_NAME" VARCHAR,
  "CATEGORY_TYPE" VARCHAR,
  "CATEGORY_SUPERTYPE" VARCHAR,
  "CATEGORY_SUBTYPE" VARCHAR,
  "VENDOR_CATEGORY_NAME" VARCHAR,
  "VENDOR_CATEGORY_TYPE" VARCHAR,
  "VENDOR_CATEGORY_SUPERTYPE" VARCHAR,
  "VENDOR_CATEGORY_SUBTYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "CONTENT_STIMULUS_XREF" (
  "CONTENT_ID" NUMBER,
  "STIMULUS_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_CONTENT_STIMULUS_XREF.CONTENT_ID"
    FOREIGN KEY ("CONTENT_ID")
      REFERENCES "CONTENT"("CONTENT_ID"),
  CONSTRAINT "FK_CONTENT_STIMULUS_XREF.STIMULUS_ID"
    FOREIGN KEY ("STIMULUS_ID")
      REFERENCES "STIMULUS"("STIMULUS_ID")
);

