CREATE TABLE "CONTACT_TYPE_XREF" (
  "CONTACT_ID" NUMBER,
  "CONTACT_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "ORGANIZATION_TYPE_XREF" (
  "ORGANIZATION_ID" NUMBER,
  "ORGANIZATION_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "ORGANIZATION_ATTRIBUTE_TYPE" (
  "ORGANIZATION_ATTRIBUTE_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "SOURCE_ATTRIBUTE_TYPE" VARCHAR,
  "ATTRIBUTE_SUPERTYPE" VARCHAR,
  "ATTRIBUTE_TYPE" VARCHAR,
  "ATTRIBUTE_SUBTYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "CONTACT" (
  "CONTACT_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CONTACT_STRING" VARCHAR,
  "EMAIL_ADDRESS" VARCHAR,
  "PHONE_NUMBER" VARCHAR,
  "SOCIAL_MEDIA" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "CONTACT_TYPE" (
  "CONTACT_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "SOURCE_CONTACT_TYPE_NAME" VARCHAR,
  "CONTACT_SUPERTYPE" VARCHAR,
  "CONTACT_TYPE" VARCHAR,
  "CONTACT_SUBTYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "ORGANIZATION_ATTRIBUTE" (
  "ORGANIZATION_ATTRIBUTE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "ORGANIZATION_ATTRIBUTE_TYPE_ID" NUMBER,
  "ATTTRIBUTE_NAME" VARCHAR,
  "ATTRIBUTE_VALUE" VARCHAR,
  "CLEAN_ATTRIBUTE_NAME" VARCHAR,
  "CLEAN_ATTRIBUTE_VALUE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_ORGANIZATION_ATTRIBUTE.ORGANIZATION_ATTRIBUTE_TYPE_ID"
    FOREIGN KEY ("ORGANIZATION_ATTRIBUTE_TYPE_ID")
      REFERENCES "ORGANIZATION_ATTRIBUTE_TYPE"("ORGANIZATION_ATTRIBUTE_TYPE_ID")
);

CREATE TABLE "ORGANIZATION_ATTRIBUTE_TYPE_HIST" (
  "ORGANIZATION_ATTRIBUTE_TYPE_ID" NUMBER,
  "ORGANIZATION_ATTRIBUTE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_ORGANIZATION_ATTRIBUTE_TYPE_HIST.ORGANIZATION_ATTRIBUTE_ID"
    FOREIGN KEY ("ORGANIZATION_ATTRIBUTE_ID")
      REFERENCES "ORGANIZATION_ATTRIBUTE"("ORGANIZATION_ATTRIBUTE_ID"),
  CONSTRAINT "FK_ORGANIZATION_ATTRIBUTE_TYPE_HIST.ORGANIZATION_ATTRIBUTE_TYPE_ID"
    FOREIGN KEY ("ORGANIZATION_ATTRIBUTE_TYPE_ID")
      REFERENCES "ORGANIZATION_ATTRIBUTE_TYPE"("ORGANIZATION_ATTRIBUTE_TYPE_ID")
);

CREATE TABLE "ORGANIZATION" (
  "ORGANIZATION_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "SOURCE_ORGANIZATION_STRING" VARCHAR,
  "SOURCE_ORGANIZATION_STRING_TYPE" VARCHAR,
  "CLEAN_ORGANIZATION_STRING" VARCHAR,
  "CLEAN_ORGANIZATION_STRING_TYPE" VARCHAR,
  "ORGANIZATION_SHORT_NAME" VARCHAR,
  "ORGANIZATION_LONG_NAME" VARCHAR,
  "ORGANIZATION_LEGAL_NAME" VARCHAR,
  "ORGANIZATION_COMMON_NAME" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "MASTER_SCHEMA" (
  "MASTER_SCHEMA_ID" NUMBER,
  "MASTER_SCHEMA_NAME" VARCHAR,
  "MASTER_SCHEMA_OWNER" VARCHAR,
  "MASTER_SCHEMA_VERSION" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

CREATE TABLE "ORGANIZATION_MASTER" (
  "ORGANIZATION_ID" NUMBER,
  "MASTER_ORGANIZATION_ID" NUMBER,
  "MASTER_SCHEMA_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_ORGANIZATION_MASTER.MASTER_ORGANIZATION_ID"
    FOREIGN KEY ("MASTER_ORGANIZATION_ID")
      REFERENCES "ORGANIZATION"("ORGANIZATION_ID"),
  CONSTRAINT "FK_ORGANIZATION_MASTER.MASTER_SCHEMA_ID"
    FOREIGN KEY ("MASTER_SCHEMA_ID")
      REFERENCES "MASTER_SCHEMA"("MASTER_SCHEMA_NAME"),
  CONSTRAINT "FK_ORGANIZATION_MASTER.ORGANIZATION_ID"
    FOREIGN KEY ("ORGANIZATION_ID")
      REFERENCES "ORGANIZATION"("ORGANIZATION_ID")
);

CREATE TABLE "PERSON_TYPE_XREF" (
  "PERSON_ID" NUMBER,
  "PERSON_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "ORGANIZATION_TYPE" (
  "ORGANIZATION_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "SOURCE_ORGANIZATION_TYPE_NAME" VARCHAR,
  "ORGANIZATION_SUPERTYPE" VARCHAR,
  "ORGANIZATION_TYPE" VARCHAR,
  "ORGANIZATION_SUBTYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "PERSON_ATTRIBUTE" (
  "PERSON_ATTRIBUTE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "ATTRIBUTE_TYPE_ID" NUMBER,
  "ATTTRIBUTE_NAME" VARCHAR,
  "ATTRIBUTE_VALUE" VARCHAR,
  "CLEAN_ATTRIBUTE_NAME" VARCHAR,
  "CLEAN_ATTRIBUTE_VALUE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "PERSON" (
  "PERSON_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "SOURCE_PERSON_STRING" VARCHAR,
  "SOURCE_PERSON_STRING_TYPE" VARCHAR,
  "CLEAN_PERSON_STRING" VARCHAR,
  "CLEAN_PERSON_STRING_TYPE" VARCHAR,
  "FIRST_NAME" VARCHAR,
  "MIDDLE_NAME" VARCHAR,
  "LAST_NAME" VARCHAR,
  "HONORIFIC" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_PERSON.DATASET_ID"
    FOREIGN KEY ("DATASET_ID")
      REFERENCES "ORGANIZATION_TYPE"("ORGANIZATION_TYPE_ID")
);

CREATE TABLE "PERSON_ATTRIBUTE_XREF" (
  "PERSON_ATTRIBUTE_ID" NUMBER,
  "PERSON_ATTRIBUTE_TYPE_ID" NUMBER,
  "PERSON_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_PERSON_ATTRIBUTE_XREF.PERSON_ATTRIBUTE_ID"
    FOREIGN KEY ("PERSON_ATTRIBUTE_ID")
      REFERENCES "PERSON_ATTRIBUTE"("PERSON_ATTRIBUTE_ID"),
  CONSTRAINT "FK_PERSON_ATTRIBUTE_XREF.PERSON_ID"
    FOREIGN KEY ("PERSON_ID")
      REFERENCES "PERSON"("PERSON_ID")
);

CREATE TABLE "ORGANIZATION_ATTRIBUTE_XREF" (
  "ORGANIZATION_ATTRIBUTE_ID" NUMBER,
  "ORGANIZATION_ATTRIBUTE_TYPE_ID" NUMBER,
  "ORGANIZATION_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_ORGANIZATION_ATTRIBUTE_XREF.ORGANIZATION_ATTRIBUTE_ID"
    FOREIGN KEY ("ORGANIZATION_ATTRIBUTE_ID")
      REFERENCES "ORGANIZATION_ATTRIBUTE"("ORGANIZATION_ATTRIBUTE_ID"),
  CONSTRAINT "FK_ORGANIZATION_ATTRIBUTE_XREF.ORGANIZATION_ID"
    FOREIGN KEY ("ORGANIZATION_ID")
      REFERENCES "ORGANIZATION"("ORGANIZATION_ID"),
  CONSTRAINT "FK_ORGANIZATION_ATTRIBUTE_XREF.ORGANIZATION_ATTRIBUTE_TYPE_ID"
    FOREIGN KEY ("ORGANIZATION_ATTRIBUTE_TYPE_ID")
      REFERENCES "ORGANIZATION_ATTRIBUTE_TYPE"("ORGANIZATION_ATTRIBUTE_TYPE_ID")
);

CREATE TABLE "PERSON_ATTRIBUTE_TYPE" (
  "PERSON_ATTRIBUTE_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "SOURCE_ATTRIBUTE_TYPE" VARCHAR,
  "ATTRIBUTE_SUPERTYPE" VARCHAR,
  "ATTRIBUTE_TYPE" VARCHAR,
  "ATTRIBUTE_SUBTYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "PERSON_ATTRIBUTE_TYPE_HIST" (
  "PERSON_ATTRIBUTE_TYPE_ID" NUMBER,
  "PERSON_ATTRIBUTE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_PERSON_ATTRIBUTE_TYPE_HIST.PERSON_ATTRIBUTE_ID"
    FOREIGN KEY ("PERSON_ATTRIBUTE_ID")
      REFERENCES "PERSON_ATTRIBUTE"("PERSON_ATTRIBUTE_ID"),
  CONSTRAINT "FK_PERSON_ATTRIBUTE_TYPE_HIST.PERSON_ATTRIBUTE_TYPE_ID"
    FOREIGN KEY ("PERSON_ATTRIBUTE_TYPE_ID")
      REFERENCES "PERSON_ATTRIBUTE_TYPE"("PERSON_ATTRIBUTE_TYPE_ID")
);

CREATE TABLE "PERSON_ADDRESS_XREF" (
  "ADDRESS_ID" NUMBER,
  "ADDRESS_TYPE_ID" NUMBER,
  "PERSON_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "ADDRESS_TYPE" (
  "ADDRESS_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "SOURCE_ADDRESS_TYPE_NAME" VARCHAR,
  "ADDRESS_SUPERTYPE" VARCHAR,
  "ADDRESS_TYPE" VARCHAR,
  "ADDRESS_SUBTYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "METADATA_LOG" (
  "METADATA_LOG_ID" NUMBER,
  "METADATA_SCHEMA_NAME" VARCHAR,
  "METADATA_SCHEMA_OWNER" VARCHAR,
  "METADATA_SCHEMA_VERSION" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

CREATE TABLE "PERSON_TYPE" (
  "PERSON_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "SOURCE_PERSON_TYPE_NAME" VARCHAR,
  "PERSON_SUPERTYPE" VARCHAR,
  "PERSON_TYPE" VARCHAR,
  "PERSON_SUBTYPE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "PERSON_MASTER" (
  "PERSON_ID" NUMBER,
  "MASTER_PERSON_ID" NUMBER,
  "MASTER_SCHEMA_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  CONSTRAINT "FK_PERSON_MASTER.MASTER_PERSON_ID"
    FOREIGN KEY ("MASTER_PERSON_ID")
      REFERENCES "PERSON"("PERSON_ID"),
  CONSTRAINT "FK_PERSON_MASTER.MASTER_SCHEMA_ID"
    FOREIGN KEY ("MASTER_SCHEMA_ID")
      REFERENCES "MASTER_SCHEMA"("MASTER_SCHEMA_NAME"),
  CONSTRAINT "FK_PERSON_MASTER.PERSON_ID"
    FOREIGN KEY ("PERSON_ID")
      REFERENCES "PERSON"("PERSON_ID")
);

CREATE TABLE "ADDRESS_TYPE_XREF" (
  "ADDRESS_ID" NUMBER,
  "ADDRESS_TYPE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "ADDRESS" (
  "ADDRESS_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "ADDRESS_STRING" VARCHAR,
  "ADDRESS_1" VARCHAR,
  "ADDRESS_2" VARCHAR,
  "ADDRESS_3" VARCHAR,
  "CITY" VARCHAR,
  "PROVINCE" VARCHAR,
  "STATE" VARCHAR,
  "REGION" VARCHAR,
  "PREFECTURE" VARCHAR,
  "COUNTRY_NAME" VARCHAR,
  "CITY_CODE" VARCHAR,
  "PROVINCE_CODE" VARCHAR,
  "STATE_CODE" VARCHAR,
  "REGION_CODE" VARCHAR,
  "PREFECTURE_CODE" VARCHAR,
  "COUNTRY_CODE" VARCHAR,
  "POSTAL_CODE" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ,
  "Field" Type
);

CREATE TABLE "PERSON_CONTACT_XREF" (
  "CONTACT_ID" NUMBER,
  "CONTACT_TYPE_ID" NUMBER,
  "PERSON_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "ORGANIZATION_CONTACT_XREF" (
  "CONTACT_ID" NUMBER,
  "CONTACT_TYPE_ID" NUMBER,
  "ORGANIZATION_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "ORGANIZATION_ADDRESS_XREF" (
  "ADDRESS_ID" NUMBER,
  "ADDRESS_TYPE_ID" NUMBER,
  "ORGANIZATION_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP_TZ
);

CREATE TABLE "DATASET" (
  "DATASET_ID" NUMBER,
  "DATASET_OWNER_ID" NUMBER,
  "DATASET_OWNER_NAME" VARCHAR,
  "DATASET_NAME" VARCHAR,
  "CURRENT_STATUS" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

