CREATE TABLE "STATUS_SCHEMA_HEADER" (
  "STATUS_SCHEMA_ID" NUMBER,
  "STATUS_SCHEMA_NAME" VARCHAR,
  "STATUS_SCHEMA_OWNER" VARCHAR,
  "STATUS_SCHEMA_VERSION" VARCHAR,
  "CURRENT_STATUS_ID" NUMBER,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

CREATE TABLE "STATUS_SCHEMA_DETAIL" (
  "STATUS_ID" NUMBER,
  "STATUS_SCHEMA_ID" NUMBER,
  "STATUS_NAME" VARCHAR,
  "STATUS_VALUE" VARCHAR,
  "SOURCE_STATUS_NAME" VARCHAR,
  "SOURCE_STATUS_VALUE" VARCHAR,
  "SOURCE_STATUS_ENUM" VARCHAR,
  "CURRENT_STATUS_ID" NUMBER,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP,
  CONSTRAINT "FK_STATUS_SCHEMA_DETAIL.STATUS_SCHEMA_ID"
    FOREIGN KEY ("STATUS_SCHEMA_ID")
      REFERENCES "STATUS_SCHEMA_HEADER"("STATUS_SCHEMA_ID")
);

CREATE TABLE "PRODUCT_KEYSET" (
  "PRODUCT_KEYSET_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "NETSUITE_ITEM_ID" VARCHAR,
  "SKU" VARCHAR,
  "UPC_CODE" VARCHAR,
  "PRODUCT_DISPLAY_NAME" VARCHAR,
  "MANUFACTURER_PART_NO" VARCHAR,
  "PRODUCT_ID" VARCHAR,
  "PRODUCT_NO" VARCHAR,
  "ITEM_NO" VARCHAR,
  "ITEM_ID" VARCHAR,
  "SFDC_INTEGRATION_ID" VARCHAR,
  "VENDOR_PART_NO" VARCHAR,
  "HYPERION_CATEGORY" VARCHAR,
  "HYPERION_SUBCATEGORY" VARCHAR,
  "HYPERION_GROUP_ID" VARCHAR,
  "PRODUCT_LINE" VARCHAR,
  "PRODUCT_DESC" VARCHAR,
  "KEYSET_FIELD_NAME_1" VARCHAR,
  "KEYSET_FIELD_VALUE_1" VARCHAR,
  "KEYSET_FIELD_NAME_2" VARCHAR,
  "KEYSET_FIELD_VALUE_2" VARCHAR,
  "KEYSET_FIELD_NAME_3" VARCHAR,
  "KEYSET_FIELD_VALUE_3" VARCHAR,
  "KEYSET_FIELD_NAME_4" VARCHAR,
  "KEYSET_FIELD_VALUE_4" VARCHAR,
  "KEYSET_FIELD_NAME_5" VARCHAR,
  "KEYSET_FIELD_VALUE_5" VARCHAR,
  "KEYSET_FIELD_NAME_N" VARCHAR,
  "KEYSET_FIELD_VALUE_N" VARCHAR,
  "CURRENT_STATUS_ID" NUMBER,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

CREATE TABLE "PRODUCT_ATTRIBUTE" (
  "PRODUCT_ATTRIBUTE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "SOURCE_ATTRIBUTE_NAME" VARCHAR,
  "SOURCE_ATTRIBUTE_VALUE" VARCHAR,
  "CLEAN_ATTRIBUTE_NAME" VARCHAR,
  "CLEAN_ATTRIBUTE_VALUE" VARCHAR,
  "LAYER1_ATTRIBUTE_NAME" VARCHAR,
  "LAYER1_ATTRIBUTE_VALUE" VARCHAR,
  "LAYERN_FIELD_NAME" VARCHAR,
  "LAYERN_FIELD_VALUE" VARCHAR,
  "CURRENT_STATUS_ID" NUMBER,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

CREATE TABLE "PRODUCT_ATTRIBUTE_XREF" (
  "PRODUCT_KEYSET_ID" NUMBER,
  "PRODUCT_ATTRIBUTE_ID" NUMBER,
  "CURRENT_STATUS_ID" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP,
  CONSTRAINT "FK_PRODUCT_ATTRIBUTE_XREF.PRODUCT_KEYSET_ID"
    FOREIGN KEY ("PRODUCT_KEYSET_ID")
      REFERENCES "PRODUCT_KEYSET"("PRODUCT_KEYSET_ID"),
  CONSTRAINT "FK_PRODUCT_ATTRIBUTE_XREF.PRODUCT_ATTRIBUTE_ID"
    FOREIGN KEY ("PRODUCT_ATTRIBUTE_ID")
      REFERENCES "PRODUCT_ATTRIBUTE"("PRODUCT_ATTRIBUTE_ID")
);

CREATE TABLE "METADATA_LOG" (
  "METADATA_LOG_ID" NUMBER,
  "METADATA_SCHEMA_NAME" VARCHAR,
  "METADATA_SCHEMA_OWNER" VARCHAR,
  "METADATA_SCHEMA_VERSION" VARCHAR,
  "CURRENT_STATUS_ID" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

CREATE TABLE "MASTER_SCHEMA" (
  "MASTER_SCHEMA_ID" NUMBER,
  "MASTER_SCHEMA_NAME" VARCHAR,
  "MASTER_SCHEMA_OWNER" VARCHAR,
  "MASTER_SCHEMA_VERSION" VARCHAR,
  "CURRENT_STATUS_ID" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

CREATE TABLE "PRODUCT_KEYSET_MASTER" (
  "PRODUCT_KEYSET_ID" NUMBER,
  "MASTER_PRODUCT_KEYSET_ID" NUMBER,
  "MASTER_SCHEMA_ID" NUMBER,
  "CURRENT_STATUS_ID" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP,
  CONSTRAINT "FK_PRODUCT_KEYSET_MASTER.PRODUCT_KEYSET_ID"
    FOREIGN KEY ("PRODUCT_KEYSET_ID")
      REFERENCES "PRODUCT_KEYSET"("PRODUCT_KEYSET_ID"),
  CONSTRAINT "FK_PRODUCT_KEYSET_MASTER.MASTER_SCHEMA_ID"
    FOREIGN KEY ("MASTER_SCHEMA_ID")
      REFERENCES "MASTER_SCHEMA"("MASTER_SCHEMA_ID"),
  CONSTRAINT "FK_PRODUCT_KEYSET_MASTER.MASTER_PRODUCT_KEYSET_ID"
    FOREIGN KEY ("MASTER_PRODUCT_KEYSET_ID")
      REFERENCES "PRODUCT_KEYSET"("PRODUCT_KEYSET_ID")
);

CREATE TABLE "PRODUCT_PRICE" (
  "PRODUCT_ATTRIBUTE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "MASTER_SCHEMA_ID" NUMBER,
  "SOURCE_ATTRIBUTE_NAME" VARCHAR,
  "SOURCE_ATTRIBUTE_VALUE" VARCHAR,
  "PRODUCT_PRICE" VARCHAR,
  "CURRENT_STATUS_ID" NUMBER,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP,
  CONSTRAINT "FK_PRODUCT_PRICE.PRODUCT_ATTRIBUTE_ID"
    FOREIGN KEY ("PRODUCT_ATTRIBUTE_ID")
      REFERENCES "PRODUCT_ATTRIBUTE"("PRODUCT_ATTRIBUTE_ID"),
  CONSTRAINT "FK_PRODUCT_PRICE.MASTER_SCHEMA_ID"
    FOREIGN KEY ("MASTER_SCHEMA_ID")
      REFERENCES "MASTER_SCHEMA"("MASTER_SCHEMA_ID")
);

CREATE TABLE "PRODUCT_COLOR" (
  "PRODUCT_ATTRIBUTE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "MASTER_SCHEMA_ID" NUMBER,
  "SOURCE_ATTRIBUTE_NAME" VARCHAR,
  "SOURCE_ATTRIBUTE_VALUE" VARCHAR,
  "PRODUCT_COLOR" VARCHAR,
  "CURRENT_STATUS_ID" NUMBER,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP,
  CONSTRAINT "FK_PRODUCT_COLOR.DATASET_ID"
    FOREIGN KEY ("DATASET_ID")
      REFERENCES "PRODUCT_ATTRIBUTE"("PRODUCT_ATTRIBUTE_ID"),
  CONSTRAINT "FK_PRODUCT_COLOR.MASTER_SCHEMA_ID"
    FOREIGN KEY ("MASTER_SCHEMA_ID")
      REFERENCES "MASTER_SCHEMA"("MASTER_SCHEMA_ID")
);

CREATE TABLE "PRODUCT_SIZE" (
  "PRODUCT_ATTRIBUTE_ID" NUMBER,
  "DATASET_ID" NUMBER,
  "MASTER_SCHEMA_ID" NUMBER,
  "SOURCE_ATTRIBUTE_NAME" VARCHAR,
  "SOURCE_ATTRIBUTE_VALUE" VARCHAR,
  "PRODUCT_SIZE" VARCHAR,
  "CURRENT_STATUS_ID" NUMBER,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP,
  CONSTRAINT "FK_PRODUCT_SIZE.MASTER_SCHEMA_ID"
    FOREIGN KEY ("MASTER_SCHEMA_ID")
      REFERENCES "MASTER_SCHEMA"("MASTER_SCHEMA_ID"),
  CONSTRAINT "FK_PRODUCT_SIZE.PRODUCT_ATTRIBUTE_ID"
    FOREIGN KEY ("PRODUCT_ATTRIBUTE_ID")
      REFERENCES "PRODUCT_ATTRIBUTE"("PRODUCT_ATTRIBUTE_ID")
);

CREATE TABLE "DATASET" (
  "DATASET_ID" NUMBER,
  "DATASET_OWNER_ID" NUMBER,
  "DATASET_OWNER_NAME" VARCHAR,
  "DATASET_NAME" VARCHAR,
  "CURRENT_STATUS_ID" VARCHAR,
  "CURRENT_STATUS_TIMESTAMP" TIMESTAMP_TZ,
  "METADATA_LOG_ID" NUMBER,
  "METADATA_LOG_TIMESTAMP" TIMESTAMP
);

